---
Title: Extra Plots
---
```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(readr)
library(ggridges)
library(ggplot2)
library(usmap)
library(dplyr)
library(tigris)
library(stringr)
# install.packages("leaflet")
library(leaflet)
library(sf)
library(visdat)
library(naniar)
library(UpSetR)
# install.packages("devtools")
library(devtools)
devtools::install_github("hrbrmstr/streamgraph")
library(RColorBrewer)
```

```{r analysis}
victims_incidents <- read_csv("../data/victims_incidents.csv")
glimpse(victims_incidents)
```


```{r}
summary(victims_incidents)
```


```{r incidents_state_map}
#plot_usmap(data = counties_data, values = "incident_count", include = .south_region, color = "black", exclude = c("OK", "KY", "WV", "MD", "DE", "DC"), labels = TRUE) + 
#  scale_fill_continuous(low = "white", high = "red", name = "Incident Count") + 
#  labs(title = "Incident Count By State")+
#  theme(legend.position = "right")
 #colorblind friendly pallete
 #colorblind friendly pallet
```

```{r incidents_count_by_state}
victims_incidents %>%
  group_by(state) %>%
  summarise(total_incidents = n()) %>%
  arrange(desc(total_incidents)) %>% 
  print()
```

``` {r incidents_alabama_counties}
fips_data <- tigris::counties(state = "Alabama", class = "sf") %>%
  select(fips = GEOID, county = NAME)

#Data cleanup steps for this map moved to memo
 
#plot_usmap(regions = "counties", data = alabama_incidents, values = "incident_count", include = "AL", color = "black") +
 #scale_fill_continuous(low = "white", high = "red", name = "Incidents Count", na.value = "white") +
  #labs(title = "Number of Incidents by County in Alabama",
   #   subtitle = "Of 203 total incidents in the state") +
  #theme(legend.position = "right")
```

``` {r leaflet-trial}
all_counties_map <- victims_incidents %>% 
  mutate(county = str_replace(county, " County", "")) %>%  # because county names don't match fips data
  group_by(state, county) %>% # Select counties as a group with the state
  summarise(incident_count = n(), .groups = 'drop') %>% # Count incidents per county
  arrange(state, county) # Arrange by state and then county

counties_data <- tigris::counties(state = c("AL", "AR", "FL", "GA", "LA", "MS", "NC", "SC", "TN", "TX", "VA"), class = "sf")|> #Grab multipolygon shapefiles of each county
  arrange(STATEFP, NAME)|> # Arrange by state and then county
  rename(county = NAME) # Rename column to "county"
  
counties_data<-counties_data|> # Convert STATEFP number to state name to allow join
  mutate(state = case_when(
    STATEFP == "01" ~ "Alabama",
    STATEFP == "05" ~ "Arkansas",
    STATEFP == "12" ~ "Florida",
    STATEFP == "13" ~ "Georgia",
    STATEFP == "22" ~ "Louisiana",
    STATEFP == "28" ~ "Mississippi",
    STATEFP == "37" ~ "North Carolina",
    STATEFP == "45" ~ "South Carolina",
    STATEFP == "47" ~ "Tennessee",
    STATEFP == "48" ~ "Texas",
    STATEFP == "51" ~ "Virginia"))|>
  select(county, state, geometry)

all_counties_map<-all_counties_map|>
  mutate(county = str_replace(county, " Parish", ""))|> # Fix Louisiana
   mutate(county = str_replace(county, "Saint ", "St. ")) #Fix "Saint"

```

```{r joins}
counties_data <- counties_data|>
  left_join(all_counties_map, by = c("state", "county")) # Joining datasets by state and then county. This includes counties with no incidents.

problems<- all_counties_map |>
  anti_join(counties_data, join_by(county))

sf_counties <- counties_data|>
  st_as_sf()

```
```{r cutreorder }
counties_data<-counties_data|>
  mutate(count_cut = cut(incident_count, breaks = c(-Inf,0.9,1.9,2.9,3.9,4.9,5.9,10.9,40.9,Inf), labels = c("Not reported","1","2","3","4","5","6-10","11-40",">40")))|>
  mutate(count_cut = ifelse(is.na(count_cut), "Not reported", as.character(count_cut)))

counties_data$count_cut <- factor(counties_data$count_cut, 
                                  levels = c("Not reported", "1", "2", "3", "4", "5", "6-10", "11-40", ">40"))
```

```{r leaflet-plots}
palcounty<-colorFactor("Reds", domain = counties_data$count_cut)

leaflet(counties_data) |>
  addProviderTiles(providers$Jawg.Streets) |>
  addPolygons(
    fillColor = ~palcounty(counties_data$count_cut),  # Color by incident count
    weight = 0.5,
    highlightOptions = highlightOptions(weight = 1,
        color = "white",
        fillOpacity = 1,
        bringToFront = TRUE),
    opacity = 1,
    color = "black",
    fillOpacity = 1,
    popup = ~paste("State: ", state, "<br>", "County: ", county, "<br>", "Deaths reported: ", incident_count, "<br>"))|>
   addLegend(position = "topleft",
            pal = palcounty,
            values = ~counties_data$count_cut, 
            title = "Deaths reported" ,
            opacity = 1)

```

```{r spaghetti plot}

data <- victims_incidents %>%
  filter(state %in% c("Alabama", "Arkansas", "Louisiana", "Mississippi", "North Carolina", "South Carolina", "Tennessee", "Texas", "Virginia")) |>
  mutate(year = incident_year_range_beg) |>
  group_by(year, state, sex) |>
  summarize(n = n())

data %>%
  drop_na(sex) |>
  ggplot( aes(x=year, y=n, group=state, color=state)) +
    geom_line(alpha = .5) +
    scale_color_viridis(discrete = TRUE) +
    geom_vline(xintercept = 1945, linetype = "dotted", color = "red") +
  geom_vline(xintercept = 1951, linetype = "dotted", color = "red") +
  annotate("rect", 
  xmin = 1945, 
  xmax = 1951, 
  ymin = 0, 
  ymax = 20, 
  alpha = 0.3, 
  fill = "lightblue") +
  labs( x = "Year", y = "Incident Count") +
    theme(
      legend.position="right",
      plot.title = element_text(size=10)) +
    ggtitle("Anti-Black Violence Incident Count by State from 1930-1954")
    theme_ipsum()
```


